### ISSUE TITLE
프로필 디자인 및 구현

### ISSUE THREAD

**Issue by HarenKei** [DefCon-Apps/ECOmunity-FE#15]
# Summary
- 프로필 페이지의 디자인 구현 예정
- 프로필 페이지에서 props 사용하여 사용자별 이름과 프로필 사진 가져오기 구현 예정

# Discription
- Redux와 같은 상태 관리 라이브러리를 이용하여 전역적으로 사용해야 할 값에 대한 처리를 할 수도 있습니다.
- 디자인 요소를 추가해보겠습니다.
- 홈으로 돌아가기 기능을 추가하겠습니다.

**Comment by rdg1029** [comment]
auth라는 모듈에서 로그인된 사용자 정보를 불러올 수 있는데
로그인 페이지(Login.tsx)에 있는 코드 참고하시면 될 듯 함니다

**Comment by HarenKei** [comment]
> auth라는 모듈에서 로그인된 사용자 정보를 불러올 수 있는데 로그인 페이지(Login.tsx)에 있는 코드 참고하시면 될 듯 함니다

와...갑부...
