### ISSUE TITLE
PostWrite 컴포넌트에 스타일 적용

### ISSUE THREAD

**Issue by rdg1029** [DefCon-Apps/ECOmunity-FE#30]
<img width="958" alt="스크린샷 2022-09-15 오후 3 28 05" src="https://user-images.githubusercontent.com/10252712/190330377-127e7e54-04fc-43db-9405-54f155f30398.png">
이거 디자인 좀 살짝 바꿔보겠슴다

**Comment by yymin1022** [comment]
와.. 마스터;;
